# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('facebook_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('insta_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_site', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_text', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_4', models.CharField(blank=True, max_length=250, null=True)),
                ('address_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('years_experience', models.IntegerField(null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('terms_conditions_date', models.DateTimeField(auto_now_add=True)),
                ('racer', models.BooleanField(default=False)),
                ('sponsor', models.BooleanField(default=False)),
                ('career_victories', models.ManyToManyField(to='drivers.CareerVictory')),
                ('identity', models.ManyToManyField(to='drivers.IdentityScans')),
                ('license_types', models.ManyToManyField(to='drivers.RacingLicenseTypes')),
                ('licenses', models.ManyToManyField(to='drivers.RacingLicenseScans')),
                ('profile_images', models.ManyToManyField(to='drivers.DriverProfile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
