# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191020_1849'),
        ('sponsors', '0002_remove_sponsors_driver_sponsored'),
        ('drivers', '0002_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='career_victories',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_types',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='profile_images',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='username',
        ),
        migrations.RemoveField(
            model_name='members',
            name='career_victories',
        ),
        migrations.RemoveField(
            model_name='members',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='members',
            name='license_types',
        ),
        migrations.RemoveField(
            model_name='members',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='members',
            name='profile_images',
        ),
        migrations.RemoveField(
            model_name='members',
            name='username',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
