# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20191020_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerVictory',
        ),
    ]
