# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='driver_sponsored',
        ),
    ]
