# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0008_auto_20191021_2100'),
        ('sponsors', '0002_remove_sponsors_driver_sponsored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='address_line_4',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='company_site',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='facebook_handle',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='insta_handle',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='profile_text',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='sign_up_date',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='sponsor_nation',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='driver_sponsored',
            field=models.ManyToManyField(to='racers.Members'),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='member_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
