# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
        ('sponsors', '0003_auto_20191021_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='boat_sponsored',
            field=models.ManyToManyField(to='boats.Boat'),
        ),
    ]
