# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_sponsors_boat_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorcontracts',
            name='file_contract',
            field=models.FileField(upload_to='sponsors/contracts'),
        ),
        migrations.AlterField(
            model_name='sponsorlogo',
            name='image',
            field=models.FileField(upload_to='sponsors/logos'),
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='driver_sponsored',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='driver_sponsored',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='member_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='racers.Members'),
        ),
    ]
