# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerVictory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', django_countries.fields.CountryField(max_length=2, null=True)),
                ('team', models.CharField(max_length=250, null=True)),
                ('year', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/profile')),
                ('expires', models.DateField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityScans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/identity')),
                ('expires', models.DateField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('facebook_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('insta_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_site', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_text', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_4', models.CharField(blank=True, max_length=250, null=True)),
                ('address_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('years_experience', models.IntegerField(null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('terms_conditions_date', models.DateTimeField(auto_now_add=True)),
                ('racer', models.BooleanField(default=False)),
                ('sponsor', models.BooleanField(default=False)),
                ('career_victories', models.ManyToManyField(to='racers.CareerVictory')),
                ('identity', models.ManyToManyField(to='racers.IdentityScans')),
            ],
        ),
        migrations.CreateModel(
            name='RacingLicenseScans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/licenses')),
                ('expires', models.DateField()),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RacingLicenseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='license_types',
            field=models.ManyToManyField(to='racers.RacingLicenseTypes'),
        ),
        migrations.AddField(
            model_name='members',
            name='licenses',
            field=models.ManyToManyField(to='racers.RacingLicenseScans'),
        ),
        migrations.AddField(
            model_name='members',
            name='profile_images',
            field=models.ManyToManyField(to='racers.DriverProfile'),
        ),
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityscans',
            name='identity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racers.IdentityTypes'),
        ),
    ]
