# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='expires',
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='file',
            field=models.FileField(upload_to='profile'),
        ),
    ]
