# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0003_members_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='racinglicensescans',
            name='license_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='racers.RacingLicenseTypes'),
        ),
    ]
