# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0005_auto_20191021_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='email_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
