# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racers', '0006_auto_20191021_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
